
//Principal root : Hello word!
GET http://localhost:3000/

### USER'S REQUESTS

### Create user
POST http://localhost:3000/users/signup/
Content-Type: application/json

{
    "userName": "william",
    "password": "1207",
    "role": "etudiant",
    "email": "william@gmail.com",
    "userInfo": "électronicien",
    "phoneNumber": "0817608201"
}

### SignIn
POST  http://localhost:3000/users/signin
Content-Type: application/json

{
    "password": "1234",
    "email": "william@gmail.com"
}
### Get the currently signed in user
GET http://localhost:3000/users/whoami

### Sign out
POST http://localhost:3000/users/signout


### get user by id
GET http://localhost:3000/users/63193748f16f1d2154e200f0

### Get user by user name
GET http://localhost:3000/users?user=william

### Delete user given id
DELETE http://localhost:3000/users/6319e8ade578345d28829139

### Update user given id Note les champs sont optionnels, ie on peut updater seulement un champ
PATCH http://localhost:3000/users/631a0cf7008092282c45abd3
Content-Type: application/json

{
    "userName": "william",
    "password": "1207",
    "email": "william@gmail.com",
    "userInfo": "électronicien",
    "phoneNumber": "0817608201"
}