
//Principal root : Hello word!
POST http://localhost:3000/auth/login



### USER'S REQUESTS

### Create user
POST http://localhost:3000/users/signup/
Content-Type: application/json

{
    "userName": "Leo",
    "password": "maz",
    "role": "ass",
    "email": "leo@gmail.com",
    "userInfo": "électronicien",
    "phoneNumber": "0817608201"
}

### SignIn
POST  http://localhost:3000/users/signin
Content-Type: application/json

{
    "password": "mutombo",
    "email": "wiam@gmail.com"
}
### get all users
POST  http://localhost:3000/users/

### get user by id
GET http://localhost:3000/X75lqYLjnHsll-IGWvrX2HYt4Hgm9Dic

### Get user by user name
GET http://localhost:3000/users?user=mutombo_exousia

### Delete user given id
DELETE http://localhost:3000/users/63d2a16593661034481ec534

### Update user given id Note les champs sont optionnels, ie on peut updater seulement un champ
PATCH http://localhost:3000/users/63d2cb983699ca2cb433fb09
Content-Type: application/json

{
   
    "password": "mutombo",
    "email": "william@gmail.com",
    "userInfo": "électronicien",
    "phoneNumber": "0817608201"
}